title: Pacturius
email: ihassin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A source of information about consumer-driven contract testing using Pact

baseurl: "/"
url: "https://www.pacturius.com"
twitter_username: itababy
github_username:  ihassin

# Build settings
theme: "just-the-docs"
color_scheme: dark

plugins:
  - jekyll-feed

#enable search
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - pipeline-inceptions-info.json
 - pipeline-inceptions-info-nodocker.json
 - build.sh
 - deploy.sh
 - spellcheck.sh
 - Rakefile
 - publish.sh

# google_analytics: "G-NL8P4DLZPJ"
