version: 0.0
os: linux
files:
  - source: _site/
    destination: /home/ubuntu/www-pacturius
permissions:
  - object: /home/ubuntu/www-pacturius
    pattern: '**'
    mode: '0755'
    owner: ubuntu
    group: ubuntu
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300
